micronaut:
  application:
    name: multipleModule
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /foo # <- This must be allowed and assets loaded.
netty:
  default:
    allocator:
      max-order: 3